### ISSUE TITLE
Location Undetectable

### ISSUE THREAD

**Issue by Kapple14** [Kapple14/KiddyGuide#1]
## GitHub Issue: Inconsistent Location Detection in KiddyGuide App

**Problem**: Location detection sporadically fails or gets stuck during app use, possibly related to Google Geoservices integration.

**Symptoms**: 
- Occasional failure on the first try.
- Inconsistency across app sessions.

**Steps to Reproduce**:
1. Open KiddyGuide App.
2. Use location-based features.
3. Observe failures/stuck behavior.

**Expected Behavior**: 
- Reliable location detection in each app usage.

**Proposed Solution**:
1. Thorough testing of Google Geoservices integration.
2. Implement robust error handling.
3. Consider alternative location services providers.

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by abhishek818** [comment]
@Kapple14  Tried repro, fetching location gets stuck infinitely in Firefox, works fine in GChrome for me. 

Tested with npm packages like current-location-geo and also tried with most downloaded package like react-geolocated (didnt tested with it since it uses hook and older version need React<18.0), But to no avail.

Seem navigator apis have this known issue for a long time now, Refer this stackoverflow [link](https://stackoverflow.com/questions/3397585/navigator-geolocation-getcurrentposition-sometimes-works-sometimes-doesnt) and you will find several other threads related : [link](https://www.google.co.in/search?q=navigator.geolocation.getcurrentposition+not+working+in+firefox&sca_esv=f4dacfe81c780abe&sxsrf=ACQVn088LjlTRsv4upLW3JqrP4TL4lW48w%3A1710964163714&source=hp&ei=wz37ZaORKa6r4-EPtcKGgAw&iflsig=ANes7DEAAAAAZftL0_0BsjUXg4pkhazNc1QGGorJxC5b&oq=navigator.geolocation+not+working+in+firefox&gs_lp=Egdnd3Mtd2l6IixuYXZpZ2F0b3IuZ2VvbG9jYXRpb24gbm90IHdvcmtpbmcgaW4gZmlyZWZveCoCCAAyBhAAGAgYHjILEAAYgAQYigUYhgNIg2VQAFjOUnAGeACQAQCYAYMBoAG3HKoBBDIuMzG4AQPIAQD4AQL4AQGYAiegAqsewgIKEAAYFhgeGA8YCsICBhAAGBYYHsICCBAAGAgYHhgNmAMAkgcENi4zM6AH06cC&sclient=gws-wiz#ip=1), Also tried every possible way defined in Firefox official support [site](https://support.mozilla.org/en-US/questions/1166084)

I feel we can go ahead with fixed values for **request timeout** and **cache expiry** (arguments of navigator.geolocation.getCurrentPosition , Refer [link](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) ), Pushing a PR for it, upto you.

**Comment by Kapple14** [comment]
I see! Thanks for pointing out the issue so precisely, but I can not see how we could fix that issue in the short term without access to a modern browser. Will close the issue as it does not seem solvable from my perspective.

**Comment by abhishek818** [comment]
@Kapple14 
Overall, its about issues with older versions of browsers/location permission settings.
But shouldnt we atleast have some timeout (and then throw error) for location fetch call ?, Else it gets stuck infinitely sometimes.
If agreed, you can review or suggest alternatives (if any) on my [PR](https://github.com/Kapple14/KiddyGuide/pull/3)

**Comment by Kapple14** [comment]
Will have a look at it, but the features do not seem for this repository. Thank you

**Comment by rogueloop** [comment]
@Kapple14 is this still open, i can give it a try

**Comment by Kapple14** [comment]
Hi @rogueloop!

Thanks for asking, but it seems to not be in the scope of this project for now. I will close this issue.
